// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDRdzPq0jo3edbNSeWDUS2UiqSlp8_-pg',
    appId: '1:735695330862:web:abe17708887f360fcbc9bf',
    messagingSenderId: '735695330862',
    projectId: 'chatapp-f0ca0',
    authDomain: 'chatapp-f0ca0.firebaseapp.com',
    storageBucket: 'chatapp-f0ca0.firebasestorage.app',
    measurementId: 'G-YY1WY205GK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsnjXIEbOJ1eDM702xHrH7DPMZq_aUrQs',
    appId: '1:735695330862:android:347cd570bea35432cbc9bf',
    messagingSenderId: '735695330862',
    projectId: 'chatapp-f0ca0',
    storageBucket: 'chatapp-f0ca0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6p5cY4er3LcVq5GUjZD3B4lpwdTUmVdg',
    appId: '1:735695330862:ios:762785c77c700baacbc9bf',
    messagingSenderId: '735695330862',
    projectId: 'chatapp-f0ca0',
    storageBucket: 'chatapp-f0ca0.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );
}
